# Generated by Django 3.2.6 on 2021-09-05 10:49

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=models.SET('no author'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
